# Generated by Django 4.2.7 on 2023-11-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_column='title', max_length=30, null=True)),
                ('description', models.TextField(db_column='description', max_length=100, null=True)),
                ('category', models.TextField(db_column='category', max_length=20, null=True)),
                ('image', models.ImageField(db_column='images', null=True, upload_to='images')),
                ('price', models.PositiveIntegerField(db_column='price', null=True)),
                ('quantity', models.PositiveIntegerField(db_column='quantity', null=True)),
                ('status', models.TextField(db_column='status', max_length='10', null=True)),
            ],
        ),
    ]
