# Generated by Django 4.2.7 on 2023-11-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name', max_length=50, null=True)),
                ('email', models.TextField(db_column='email', max_length=70, null=True)),
                ('mob', models.TextField(db_column='mob', max_length=15, null=True)),
                ('cf_pswd', models.TextField(db_column='password', max_length=100, null=True)),
            ],
            options={
                'db_table': 'customer_registration',
            },
        ),
    ]
