# Generated by Django 4.2.7 on 2023-11-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.TextField(db_column='name', max_length=50)),
                ('p_quantity', models.PositiveIntegerField(db_column='quantity')),
                ('p_price', models.PositiveIntegerField(db_column='price')),
                ('p_total', models.PositiveIntegerField(db_column='total')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
