# Generated by Django 4.2.7 on 2023-11-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='p_image',
            field=models.ImageField(db_column='image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cart',
            name='p_name',
            field=models.TextField(db_column='name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='p_price',
            field=models.PositiveIntegerField(db_column='price', null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='p_quantity',
            field=models.PositiveIntegerField(db_column='quantity', null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='p_total',
            field=models.PositiveIntegerField(db_column='total', null=True),
        ),
    ]
