# Generated by Django 4.2.7 on 2023-11-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_cart_p_image_alter_cart_p_name_alter_cart_p_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.TextField(db_column='name', max_length=50, null=True)),
                ('c_email', models.TextField(db_column='email', max_length=50, null=True)),
                ('c_mob', models.TextField(db_column='mobile', max_length=12, null=True)),
                ('c_pswd', models.TextField(db_column='password', max_length=100, null=True)),
                ('otp', models.TextField(db_column='otp', max_length=6, null=True)),
                ('status', models.TextField(db_column='status', max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
