# Generated by Django 4.2.7 on 2023-11-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
